// Generated by ReScript, PLEASE EDIT WITH CARE


var Backend = {};

var Provider = {};

function MakeDnd(DO, DR, CP) {
  var Monitor = {};
  var DragSourceMonitor = {};
  var UseDrop = {};
  var UseDrag = {};
  return {
          Monitor: Monitor,
          DragSourceMonitor: DragSourceMonitor,
          UseDrop: UseDrop,
          UseDrag: UseDrag
        };
}

export {
  Backend ,
  Provider ,
  MakeDnd ,
  
}
/* No side effect */
