// Generated by ReScript, PLEASE EDIT WITH CARE


function MakeUseDragLayer(DO, CP) {
  var DragLayerMonitor = {};
  var UseDragLayer = {};
  return {
          DragLayerMonitor: DragLayerMonitor,
          UseDragLayer: UseDragLayer
        };
}

function MakeUseDrop(DO, DR, CP) {
  var DropTargetMonitor = {};
  var UseDrop = {};
  return {
          DropTargetMonitor: DropTargetMonitor,
          UseDrop: UseDrop
        };
}

function MakeUseDrag(DO, DR, CP) {
  var DragSourceMonitor = {};
  var UseDrag = {};
  return {
          DragSourceMonitor: DragSourceMonitor,
          UseDrag: UseDrag
        };
}

var Backend = {};

var Provider = {};

export {
  MakeUseDragLayer ,
  MakeUseDrop ,
  MakeUseDrag ,
  Backend ,
  Provider ,
  
}
/* No side effect */
