// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventEmitter$NodeJs from "rescript-nodejs/src/EventEmitter.mjs";

EventEmitter$NodeJs.Make({});

var Events = {
  connection: "connection"
};

var Make = {};

export {
  Events ,
  Make ,
  
}
/*  Not a pure module */
