// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$WebSocket from "./WebSocket.mjs";

var Make = {};

var ServerEvents = {
  connection: "connection",
  error: "error",
  headers: "headers",
  close: "close",
  listening: "listening"
};

var readyStateToInt = $$WebSocket.readyStateToInt;

var binaryTypeToString = $$WebSocket.binaryTypeToString;

var RawData = $$WebSocket.RawData;

var EventWithThis = $$WebSocket.EventWithThis;

var ClientEvents = $$WebSocket.ClientEvents;

var makeSendOptions = $$WebSocket.makeSendOptions;

var makeOptions = $$WebSocket.makeOptions;

export {
  readyStateToInt ,
  binaryTypeToString ,
  RawData ,
  EventWithThis ,
  ClientEvents ,
  makeSendOptions ,
  makeOptions ,
  Make ,
  ServerEvents ,
  
}
/* No side effect */
