// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventEmitter$NodeJs from "rescript-nodejs/src/EventEmitter.mjs";

EventEmitter$NodeJs.Make({});

var Events = {
  message: "message"
};

var $$WebSocket = {
  Events: Events
};

EventEmitter$NodeJs.Make({});

var Events$1 = {
  connection: "connection"
};

var WebSocketServer = {
  Events: Events$1
};

var MakeWebSocketServer = {};

export {
  $$WebSocket ,
  WebSocketServer ,
  MakeWebSocketServer ,
  
}
/*  Not a pure module */
