// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WsWebSocket from "./WsWebSocket.mjs";

var Make = {};

var ServerEvents = {
  connection: "connection",
  error: "error",
  headers: "headers",
  close: "close",
  listening: "listening"
};

var readyStateToInt = WsWebSocket.readyStateToInt;

var binaryTypeToString = WsWebSocket.binaryTypeToString;

var RawData = WsWebSocket.RawData;

var EventWithThis = WsWebSocket.EventWithThis;

var ClientEvents = WsWebSocket.ClientEvents;

var makeSendOptions = WsWebSocket.makeSendOptions;

var makeOptions = WsWebSocket.makeOptions;

export {
  readyStateToInt ,
  binaryTypeToString ,
  RawData ,
  EventWithThis ,
  ClientEvents ,
  makeSendOptions ,
  makeOptions ,
  Make ,
  ServerEvents ,
  
}
/* WsWebSocket Not a pure module */
