// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Base from "../components/Base.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";

function AuthorizationScreen(Props) {
  var onMessage = Props.onMessage;
  var match = React.useState(function () {
        return "";
      });
  var setLogin = match[1];
  var login = match[0];
  return React.createElement("div", {
              className: "m-2"
            }, React.createElement(Base.Heading.make, {
                  size: /* H5 */3,
                  children: Utils.uiStr("Authorization")
                }), React.createElement("span", undefined, Utils.uiStr("Login:")), React.createElement(Base.Input.make, {
                  value: login,
                  onChange: (function (value) {
                      return Curry._1(setLogin, (function (param) {
                                    return value;
                                  }));
                    }),
                  className: "my-2"
                }), React.createElement(Base.Button.make, {
                  onClick: (function (param) {
                      return Curry._1(onMessage, {
                                  TAG: /* Register */0,
                                  _0: login
                                });
                    }),
                  children: Utils.uiStr("Register")
                }));
}

var make = AuthorizationScreen;

export {
  make ,
  
}
/* Base Not a pure module */
