// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Base from "../components/Base.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.js";
import * as React from "react";

function LobbySetupScreen(Props) {
  var player = Props.player;
  var onMessage = Props.onMessage;
  var match = React.useState(function () {
        return "";
      });
  var setGameId = match[1];
  var gameId = match[0];
  return React.createElement("div", {
              className: "m-2"
            }, React.createElement(Base.Heading.make, {
                  size: /* H5 */3,
                  children: Utils.uiStr("Lobby select")
                }), React.createElement(Base.Button.make, {
                  onClick: (function (param) {
                      return Curry._1(onMessage, {
                                  TAG: /* Lobby */3,
                                  _0: /* Create */0,
                                  _1: player.id,
                                  _2: ""
                                });
                    }),
                  children: Utils.uiStr("New")
                }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("span", undefined, Utils.uiStr("Connect:")), React.createElement(Base.Input.make, {
                  value: gameId,
                  onChange: (function (value) {
                      return Curry._1(setGameId, (function (param) {
                                    return value;
                                  }));
                    }),
                  className: "my-2"
                }), React.createElement(Base.Button.make, {
                  onClick: (function (param) {
                      return Curry._1(onMessage, {
                                  TAG: /* Lobby */3,
                                  _0: /* Enter */1,
                                  _1: player.id,
                                  _2: gameId
                                });
                    }),
                  children: Utils.uiStr("Connect")
                }));
}

var make = LobbySetupScreen;

export {
  make ,
  
}
/* Base Not a pure module */
