// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";
import * as GameUtils from "../fool/GameUtils.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function hook(game, player) {
  var match = React.useState(function () {
        return [
                undefined,
                undefined
              ];
      });
  var setBeat = match[1];
  var match$1 = match[0];
  var handleSelectToBeat = function (isToCard, card) {
    return Curry._1(setBeat, (function (param) {
                  var beatBy = param[1];
                  var toBeat = param[0];
                  if (isToCard) {
                    var isSame = Belt_Option.getWithDefault(Belt_Option.map(toBeat, (function (param) {
                                return Utils.equals(card, param);
                              })), false);
                    if (isSame) {
                      return [
                              undefined,
                              beatBy
                            ];
                    } else {
                      return [
                              card,
                              beatBy
                            ];
                    }
                  }
                  var isSame$1 = Belt_Option.getWithDefault(Belt_Option.map(beatBy, (function (param) {
                              return Utils.equals(card, param);
                            })), false);
                  if (isSame$1) {
                    return [
                            toBeat,
                            undefined
                          ];
                  } else {
                    return [
                            toBeat,
                            card
                          ];
                  }
                }));
  };
  var isDefender = GameUtils.isDefender(game, player);
  React.useEffect((function () {
          if (!isDefender) {
            Curry._1(setBeat, (function (param) {
                    return [
                            undefined,
                            undefined
                          ];
                  }));
          }
          
        }), [isDefender]);
  return {
          toBeat: match$1[0],
          beatBy: match$1[1],
          setBeat: setBeat,
          handleSelectToBeat: handleSelectToBeat
        };
}

export {
  hook ,
  
}
/* react Not a pure module */
