// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function delay(send, msg, timeoutOpt, param) {
  var timeout = timeoutOpt !== undefined ? timeoutOpt : 100;
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(Curry._1(send, msg));
                      }), timeout);
                
              }));
}

export {
  delay ,
  
}
/* No side effect */
