// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function delay(send, msg, timeoutOpt, param) {
  var timeout = timeoutOpt !== undefined ? timeoutOpt : 100;
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(Curry._1(send, msg));
                      }), timeout);
                
              }));
}

function autologin(sendMessage, playerId, sessionId, gameId, isOwnerOpt, param) {
  var match = React.useState(function () {
        return false;
      });
  var setIsLoaded = match[1];
  var isLoaded = match[0];
  React.useEffect((function () {
          if (!isLoaded) {
            Curry._1(setIsLoaded, (function (param) {
                    return true;
                  }));
          }
          
        }), [
        sendMessage,
        isLoaded
      ]);
  
}

function startServer(param) {
  var match = React.useState(function () {
        return false;
      });
  var setIsLoaded = match[1];
  var isLoaded = match[0];
  React.useEffect((function () {
          if (!isLoaded) {
            fetch("/api/server").then(function (param) {
                  Curry._1(setIsLoaded, (function (param) {
                          return true;
                        }));
                  return Promise.resolve(1);
                });
          }
          
        }), [isLoaded]);
  return isLoaded;
}

export {
  delay ,
  autologin ,
  startServer ,
  
}
/* react Not a pure module */
