// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function hook(toBeat, beatBy, setBeat, onMove) {
  var handleBeat = function (param) {
    if (toBeat !== undefined && beatBy !== undefined) {
      Curry._1(setBeat, (function (param) {
              return [
                      undefined,
                      undefined
                    ];
            }));
      return Curry._1(onMove, {
                  TAG: /* Beat */0,
                  _0: toBeat,
                  _1: beatBy
                });
    }
    
  };
  var handleTake = function (param) {
    Curry._1(setBeat, (function (param) {
            return [
                    undefined,
                    undefined
                  ];
          }));
    return Curry._1(onMove, /* Take */0);
  };
  var handleMove = function (card) {
    return Curry._1(onMove, {
                TAG: /* Move */1,
                _0: card
              });
  };
  var handlePass = function (param) {
    return Curry._1(onMove, /* Pass */1);
  };
  return {
          handleBeat: handleBeat,
          handleTake: handleTake,
          handleMove: handleMove,
          handlePass: handlePass
        };
}

export {
  hook ,
  
}
/* No side effect */
