// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function hook(onMove) {
  var handleBeat = function (toCard, byCard) {
    return Curry._1(onMove, {
                TAG: /* Beat */0,
                _0: toCard,
                _1: byCard
              });
  };
  var handleTake = function (param) {
    return Curry._1(onMove, /* Take */0);
  };
  var handleMove = function (card) {
    return Curry._1(onMove, {
                TAG: /* Move */1,
                _0: card
              });
  };
  var handlePass = function (param) {
    return Curry._1(onMove, /* Pass */1);
  };
  return {
          handleBeat: handleBeat,
          handleTake: handleTake,
          handleMove: handleMove,
          handlePass: handlePass
        };
}

export {
  hook ,
  
}
/* No side effect */
