// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "../fool/Game.mjs";
import * as Utils from "../Utils.mjs";
import * as Player from "../fool/Player.mjs";
import * as Socket from "../Socket.mjs";
import * as $$Storage from "./Storage.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as GameUtils from "../fool/GameUtils.mjs";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

var gamesInLobby = $$Storage.LobbyGameMap.empty(undefined);

var gamesInProgress = $$Storage.ProgressGameMap.empty(undefined);

var players = $$Storage.PlayersMap.empty(undefined);

function initiateGame(param) {
  var alicePlayer = $$Storage.PlayersMap.create(players, "alice");
  var bobPlayer = $$Storage.PlayersMap.create(players, "bob");
  var tmp;
  if (alicePlayer.TAG === /* Ok */0) {
    var alice = alicePlayer._0;
    if (bobPlayer.TAG === /* Ok */0) {
      var bob = bobPlayer._0;
      tmp = Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.flatMap($$Storage.LobbyGameMap.create(gamesInLobby, alice), (function (game) {
                                  return Game.enterGame(game, bob);
                                })), (function (game) {
                              return Game.toggleReady(game, alice);
                            })), (function (game) {
                          return Game.toggleReady(game, bob);
                        })), (function (game) {
                      $$Storage.LobbyGameMap.set(gamesInLobby, game.gameId, game);
                      return {
                              TAG: /* Ok */0,
                              _0: game
                            };
                    })), (function (game) {
                  return $$Storage.ProgressGameMap.create(gamesInProgress, game);
                })), (function (game) {
              $$Storage.LobbyGameMap.remove(gamesInLobby, game.gameId);
              return {
                      TAG: /* Ok */0,
                      _0: game
                    };
            }));
    } else {
      tmp = {
        TAG: /* Error */1,
        _0: "Can't create alice or bob"
      };
    }
  } else {
    tmp = {
      TAG: /* Error */1,
      _0: "Can't create alice or bob"
    };
  }
  console.log(tmp, "game created");
  
}

function startGame(gameId) {
  var nextGame = Belt_Result.flatMap($$Storage.LobbyGameMap.get(gamesInLobby, gameId), Game.startGame);
  if (nextGame.TAG !== /* Ok */0) {
    return Socket.SServer.broadcast(gameId, {
                error: nextGame._0
              });
  }
  var game = nextGame._0;
  $$Storage.ProgressGameMap.set(gamesInProgress, gameId, game);
  return Belt_List.forEach(game.players, (function (player) {
                return Socket.SServer.send(player, Game.toObject(Game.maskForPlayer(player, game)));
              }));
}

function dispatch(gameId, playerId, action) {
  var game = $$Storage.ProgressGameMap.get(gamesInProgress, gameId);
  var player = Belt_Result.flatMap(game, (function (game) {
          return Utils.toResult(GameUtils.findPlayerById(game, playerId), "Player " + playerId + " not found");
        }));
  console.log("[predispatch]", Belt_Result.map(game, Game.toObject), Belt_Result.map(player, Player.toObject), Game.actionToObject(action));
  var nextGame = Belt_Result.flatMap(player, (function (player) {
          return Belt_Result.flatMap(game, (function (game) {
                        return Game.dispatch(game, player, action);
                      }));
        }));
  var result;
  if (nextGame.TAG === /* Ok */0) {
    var game$1 = nextGame._0;
    if (player.TAG === /* Ok */0) {
      $$Storage.ProgressGameMap.set(gamesInProgress, game$1.gameId, game$1);
      result = {
        TAG: /* Ok */0,
        _0: Game.maskForPlayer(player._0, game$1)
      };
    } else {
      result = {
        TAG: /* Error */1,
        _0: player._0
      };
    }
  } else {
    result = {
      TAG: /* Error */1,
      _0: nextGame._0
    };
  }
  if (result.TAG === /* Ok */0) {
    console.log("[dispatch] ok ", Game.toObject(result._0));
    return ;
  }
  console.log("[dispatch] error ", result._0);
  
}

export {
  gamesInLobby ,
  gamesInProgress ,
  players ,
  initiateGame ,
  startGame ,
  dispatch ,
  
}
/* gamesInLobby Not a pure module */
