// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ws from "ws";
import * as WsWebSocket from "../bindings/WsWebSocket.mjs";
import * as GameInstance from "./GameInstance.mjs";
import * as WsWebSocketServer from "../bindings/WsWebSocketServer.mjs";

var wsServer = new Ws.WebSocketServer({
      backlog: 101,
      clientTracking: true,
      maxPayload: 104857600,
      noServer: false,
      path: "/ws",
      server: restartServer(),
      skipUTF8Validation: true
    });

wsServer.on(WsWebSocketServer.ServerEvents.connection, (function (ws, param) {
        ws.on(WsWebSocket.ClientEvents.open_, (function () {
                    var client = this ;
                    console.log("connection open");
                    client.send("connected");
                    
                  })).on(WsWebSocket.ClientEvents.message, (function (msg, param) {
                  console.log("msg:", WsWebSocket.RawData.toString(msg));
                  
                })).on(WsWebSocket.ClientEvents.close, (function (param, param$1) {
                console.log("connection close");
                
              }));
        
      }));

function $$default(param, res) {
  GameInstance.initiateGame(undefined);
  res.end(Buffer.from("response"));
  
}

export {
  $$default ,
  $$default as default,
  
}
/* wsServer Not a pure module */
