// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Url from "url";
import * as $$String from "rescript/lib/es6/string.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Querystring from "querystring";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function getCookies(req) {
  return Belt_Option.getWithDefault(Belt_Option.map(req.headers.cookie, (function (cookie) {
                    return Belt_List.reduce(Belt_List.map(Belt_List.map(Belt_List.map($$String.split_on_char(/* ';' */59, cookie), (function (param) {
                                              return $$String.split_on_char(/* '=' */61, param);
                                            })), (function (cookie) {
                                          return Belt_List.map(cookie, $$String.trim);
                                        })), (function (keyValue) {
                                      return [
                                              Belt_List.get(keyValue, 0),
                                              Belt_List.get(keyValue, 1)
                                            ];
                                    })), undefined, (function (acc, param) {
                                  var value = param[1];
                                  var key = param[0];
                                  if (key !== undefined && value !== undefined) {
                                    return Belt_MapString.set(acc, key, value);
                                  } else {
                                    return acc;
                                  }
                                }));
                  })), undefined);
}

function getUrl(req, protocol) {
  return Belt_Option.map(Belt_Option.flatMap(Belt_Option.map(Caml_option.some(req), (function (prim) {
                        return prim.headers;
                      })), (function (headers) {
                    return headers.host;
                  })), (function (host) {
                return new Url.URL(req.url, protocol + "://" + host);
              }));
}

function getSearchParams(url) {
  return Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.map(Belt_Option.map(url, (function (url) {
                            return url.search;
                          })), (function (search) {
                        return search.slice(1);
                      })), (function (search) {
                    return Querystring.decode(search);
                  })), {});
}

function getParam(params, name) {
  return Belt_Option.map(Js_dict.get(params, name), (function (value) {
                if (Array.isArray(value)) {
                  return value.join("");
                } else {
                  return value;
                }
              }));
}

export {
  getCookies ,
  getUrl ,
  getSearchParams ,
  getParam ,
  
}
/* url Not a pure module */
