// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ws from "../bindings/Ws.mjs";
import * as Ws$1 from "ws";

function $$default(param, res) {
  var wsServer = new Ws$1.WebSocketServer({
        backlog: 100,
        clientTracking: true,
        maxPayload: 104857600,
        noServer: false,
        path: "/ws",
        server: restartServer(),
        skipUTF8Validation: true
      });
  wsServer.addListener(Ws.WebSocketServer.Events.connection, (function (ws) {
          ws.addListener(Ws.$$WebSocket.Events.message, (function (msg) {
                  console.log("msg:", msg.toString());
                  
                }));
          
        }));
  res.end(Buffer.from("response"));
  
}

export {
  $$default ,
  $$default as default,
  
}
/* Ws Not a pure module */
