// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";

function Base$Button(Props) {
  var disabledOpt = Props.disabled;
  var classNameOpt = Props.className;
  var onClickOpt = Props.onClick;
  var children = Props.children;
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var onClick = onClickOpt !== undefined ? onClickOpt : Utils.noop;
  return React.createElement("button", {
              className: Utils.cx([
                    className,
                    "inline-block px-6 py-2.5",
                    "bg-blue-600 text-white font-medium text-xs leading-tight uppercase",
                    "rounded shadow-md",
                    "transition duration-150 ease-in-out",
                    disabled ? "pointer-events-none opacity-60" : "hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg"
                  ]),
              disabled: disabled,
              type: "button",
              onClick: onClick
            }, children);
}

var Button = {
  make: Base$Button
};

function Base$Switch(Props) {
  var disabledOpt = Props.disabled;
  var checked = Props.checked;
  var onClick = Props.onClick;
  var text = Props.text;
  var classNameOpt = Props.className;
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: Utils.cx([
                    "form-check form-switch",
                    className
                  ])
            }, React.createElement("input", {
                  className: Utils.cx([
                        "form-check-input appearance-none w-9 -ml-10 loat-left h-5 align-top",
                        "rounded-full f",
                        "bg-white bg-no-repeat bg-contain bg-gray-300",
                        "focus:outline-none cursor-pointer shadow-sm",
                        disabled ? "pointer-events-none filter-none opacity-50" : ""
                      ]),
                  id: "flexSwitchCheckDefault",
                  role: "switch",
                  checked: checked,
                  disabled: disabled,
                  type: "checkbox",
                  onChange: onClick
                }), React.createElement("label", {
                  className: Utils.cx([
                        "form-check-label inline-block text-gray-800",
                        disabled ? "opacity-50" : ""
                      ]),
                  disabled: disabled,
                  htmlFor: "flexSwitchCheckDefault"
                }, Utils.uiStr(text)));
}

var Switch = {
  make: Base$Switch
};

function Base$Input(Props) {
  var value = Props.value;
  var onChange = Props.onChange;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("input", {
              className: Utils.cx([
                    "form-control block px-3 py-1.5",
                    "text-base font-normal text-gray-700",
                    "bg-white bg-clip-padding",
                    "border border-solid border-gray-300 rounded",
                    "transition ease-in-out",
                    "focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
                    className
                  ]),
              type: "text",
              value: value,
              onChange: (function (e) {
                  return Curry._1(onChange, e.target.value);
                })
            });
}

var Input = {
  make: Base$Input
};

export {
  Button ,
  Switch ,
  Input ,
  
}
/* react Not a pure module */
