// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.mjs";
import * as React from "react";

function Base$Button(Props) {
  var disabledOpt = Props.disabled;
  var pressedOpt = Props.pressed;
  var classNameOpt = Props.className;
  var onClickOpt = Props.onClick;
  var children = Props.children;
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var pressed = pressedOpt !== undefined ? pressedOpt : false;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var onClick = onClickOpt !== undefined ? onClickOpt : Utils.noop;
  return React.createElement("button", {
              className: Utils.cx([
                    className,
                    "p-1 border rounded-md border-solid border-slate-500 bg-slate-100 shadow-sm hover:shadow-md",
                    pressed ? Utils.selected : "",
                    disabled ? "border-slate-400 text-slate-400 cursor-not-allowed shadow-none hover:shadow-none" : ""
                  ]),
              disabled: disabled,
              onClick: onClick
            }, children);
}

var Button = {
  make: Base$Button
};

export {
  Button ,
  
}
/* react Not a pure module */
