// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../fool/Card.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function suitToColor(suit) {
  switch (suit) {
    case /* Hearts */1 :
    case /* Diamonds */2 :
        return "text-red-900 dark:text-cyan-300";
    case /* Spades */0 :
    case /* Clubs */3 :
        return "text-slate-500";
    
  }
}

function CardUI$CardUIBase(Props) {
  var classNameOpt = Props.className;
  var disabledOpt = Props.disabled;
  var selectedOpt = Props.selected;
  var onClickOpt = Props.onClick;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var selected = selectedOpt !== undefined ? selectedOpt : false;
  var onClick = onClickOpt !== undefined ? onClickOpt : Utils.noop;
  return React.createElement("div", {
              className: Utils.cx([
                    "relative w-12 h-16",
                    "border rounded-md border-solid border-slate-500",
                    "cursor-pointer select-none",
                    disabled ? "border-slate-400" : "",
                    selected ? Utils.selected : Utils.unselected,
                    className
                  ]),
              onClick: disabled ? Utils.noop : onClick
            }, children);
}

var CardUIBase = {
  make: CardUI$CardUIBase
};

function CardUI$CardUILocal(Props) {
  var classNameOpt = Props.className;
  var disabledOpt = Props.disabled;
  var selectedOpt = Props.selected;
  var card = Props.card;
  var onClickOpt = Props.onClick;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var selected = selectedOpt !== undefined ? selectedOpt : false;
  var onClick = onClickOpt !== undefined ? onClickOpt : Utils.noop;
  return React.createElement(CardUI$CardUIBase, {
              className: Utils.cx([
                    className,
                    disabled ? "text-slate-300" : suitToColor(card[0])
                  ]),
              disabled: disabled,
              selected: selected,
              onClick: (function (param) {
                  return Curry._1(onClick, card);
                }),
              children: null
            }, React.createElement("div", {
                  className: "absolute text-[18px] leading-[18px] inset-1"
                }, Utils.uiStr(Card.suitToString(card[0]))), React.createElement("div", {
                  className: "absolute top-1/2 left-1/2 font-bold text-[18px] leading-[18px] translate-y-[-50%] translate-x-[-50%]"
                }, Utils.uiStr(Card.rankToString(card[1]))));
}

var CardUILocal = {
  make: CardUI$CardUILocal
};

function CardUI$empty(Props) {
  var classNameOpt = Props.className;
  var onClickOpt = Props.onClick;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var onClick = onClickOpt !== undefined ? onClickOpt : Utils.noop;
  return React.createElement(CardUI$CardUIBase, {
              className: Utils.cx([
                    className,
                    "overflow-hidden"
                  ]),
              onClick: onClick,
              children: React.createElement("div", {
                    className: "absolute w-full h-full bg-gradient-to-tl from-purple-400 to-pink-400 bg-opacity-50"
                  })
            });
}

function CardUI(Props) {
  var classNameOpt = Props.className;
  var card = Props.card;
  var onClickOpt = Props.onClick;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var onClick = onClickOpt !== undefined ? onClickOpt : Utils.noop;
  return React.createElement(CardUI$CardUILocal, {
              className: className,
              card: card,
              onClick: onClick
            });
}

function CardUI$trump(Props) {
  var suit = Props.suit;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: Utils.cx([
                    className,
                    suitToColor(suit)
                  ])
            }, Utils.uiStr(Card.suitToString(suit)));
}

function CardUI$deck(Props) {
  var deck = Props.deck;
  var classNameOpt = Props.className;
  var disabledOpt = Props.disabled;
  var isCardSelectedOpt = Props.isCardSelected;
  var isCardDisabledOpt = Props.isCardDisabled;
  var onCardClickOpt = Props.onCardClick;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  var isCardSelected = isCardSelectedOpt !== undefined ? isCardSelectedOpt : (function (param) {
        return false;
      });
  var isCardDisabled = isCardDisabledOpt !== undefined ? isCardDisabledOpt : (function (param) {
        return false;
      });
  var onCardClick = onCardClickOpt !== undefined ? onCardClickOpt : Utils.noop;
  if (deck) {
    return React.createElement("div", {
                className: Utils.cx([
                      className,
                      "leading"
                    ])
              }, Utils.uiList(deck, (function (card) {
                      return React.createElement(CardUI$CardUILocal, {
                                  className: "inline-block mx-1",
                                  disabled: disabled || Curry._1(isCardDisabled, card),
                                  selected: Curry._1(isCardSelected, card),
                                  card: card,
                                  onClick: onCardClick,
                                  key: Card.cardToString(card)
                                });
                    })));
  } else {
    return React.createElement("div", {
                className: className
              }, Utils.uiStr("No cards in deck"));
  }
}

function CardUI$table(Props) {
  var classNameOpt = Props.className;
  var isCardSelectedOpt = Props.isCardSelected;
  var isCardDisabledOpt = Props.isCardDisabled;
  var table = Props.table;
  var onCardClickOpt = Props.onCardClick;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var isCardSelected = isCardSelectedOpt !== undefined ? isCardSelectedOpt : (function (param) {
        return false;
      });
  var isCardDisabled = isCardDisabledOpt !== undefined ? isCardDisabledOpt : (function (param) {
        return false;
      });
  var onCardClick = onCardClickOpt !== undefined ? onCardClickOpt : Utils.noop;
  return React.createElement("div", {
              className: className
            }, table ? Utils.uiList(table, (function (param) {
                      var by = param[1];
                      var to = param[0];
                      return React.createElement("div", {
                                  key: Card.cardToString(to) + Belt_Option.getWithDefault(Belt_Option.map(by, Card.cardToString), ""),
                                  className: "inline-block mx-1"
                                }, React.createElement(CardUI$CardUILocal, {
                                      disabled: Belt_Option.isSome(by) || Curry._1(isCardDisabled, to),
                                      selected: Curry._1(isCardSelected, to),
                                      card: to,
                                      onClick: onCardClick
                                    }), by !== undefined ? React.createElement(CardUI$CardUILocal, {
                                        disabled: Belt_Option.isSome(by),
                                        card: by
                                      }) : React.createElement("div", undefined, Utils.uiStr("None")));
                    })) : Utils.uiStr("Table empty"));
}

var empty = CardUI$empty;

var make = CardUI;

var trump = CardUI$trump;

var deck = CardUI$deck;

var table = CardUI$table;

export {
  suitToColor ,
  CardUIBase ,
  CardUILocal ,
  empty ,
  make ,
  trump ,
  deck ,
  table ,
  
}
/* react Not a pure module */
