// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dnd from "rescript-dnd/src/Dnd.mjs";
import * as Caml from "rescript/lib/es6/caml.js";
import * as Card from "../fool/Card.mjs";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

var Id = {};

function eq(c1, c2) {
  return Card.cardToString(c1) === Card.cardToString(c2);
}

function cmp(c1, c2) {
  return Caml.caml_string_compare(Card.cardToString(c1), Card.cardToString(c2));
}

var Comparable = Belt_Id.MakeComparable({
      cmp: cmp
    });

function make(param) {
  return Belt_Map.make(Comparable);
}

var $$Map = {
  make: make
};

var CardId = {
  Id: Id,
  eq: eq,
  cmp: cmp,
  Comparable: Comparable,
  $$Map: $$Map
};

var Id$1 = {};

var eq$1 = Caml_obj.caml_equal;

var cmp$1 = Caml_obj.caml_compare;

var Comparable$1 = Belt_Id.MakeComparable({
      cmp: cmp$1
    });

function make$1(param) {
  return Belt_Map.make(Comparable$1);
}

var $$Map$1 = {
  make: make$1
};

var DeckId = {
  Id: Id$1,
  eq: eq$1,
  cmp: cmp$1,
  Comparable: Comparable$1,
  $$Map: $$Map$1
};

var DraggableItem = {
  eq: eq,
  cmp: cmp
};

var DroppableContainer = {
  eq: eq$1,
  cmp: cmp$1
};

var Cards = Dnd.Make(DraggableItem, DroppableContainer);

export {
  CardId ,
  DeckId ,
  DraggableItem ,
  DroppableContainer ,
  Cards ,
  
}
/* Comparable Not a pure module */
