// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";
import * as GameUI from "./GameUI.mjs";
import * as ClientUI from "./ClientUI.mjs";

function InProgressScreen(Props) {
  var game = Props.game;
  var playerId = Props.playerId;
  var onMessage = Props.onMessage;
  return React.createElement("div", undefined, React.createElement(GameUI.InProgressUI.make, {
                  game: game
                }), React.createElement("div", {
                  className: "flex flex-wrap"
                }, Utils.uiList(game.players, (function (player) {
                        return React.createElement(ClientUI.make, {
                                    className: "m-1 flex-initial w-96",
                                    player: player,
                                    isOwner: player.id === playerId,
                                    game: game,
                                    onMove: (function (move) {
                                        return Curry._1(onMessage, {
                                                    TAG: /* Progress */4,
                                                    _0: move,
                                                    _1: playerId,
                                                    _2: game.gameId
                                                  });
                                      }),
                                    key: player.id
                                  });
                      }))));
}

var make = InProgressScreen;

export {
  make ,
  
}
/* react Not a pure module */
