// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../utils/Utils.mjs";
import * as React from "react";
import * as StackUI from "./StackUI.mjs";
import * as PlayerUI from "./PlayerUI.mjs";

function OpponentUI(Props) {
  var player = Props.player;
  var className = Props.className;
  var isDefender = Props.isDefender;
  var isAttacker = Props.isAttacker;
  return React.createElement("div", {
              className: Utils.cx([
                    "flex flex-col gap-2",
                    className
                  ])
            }, React.createElement(StackUI.opponent, {
                  deck: player.cards
                }), React.createElement("div", {
                  className: "vertial-align"
                }, React.createElement(PlayerUI.Short.make, {
                      className: "inline-block",
                      player: player
                    }), Utils.uiStr(isDefender ? " 🛡️" : ""), Utils.uiStr(isAttacker ? " 🔪" : "")));
}

var make = OpponentUI;

export {
  make ,
  
}
/* Utils Not a pure module */
