// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../utils/Utils.mjs";
import * as React from "react";
import * as DeckUI from "./DeckUI.mjs";

function PlayerUI$Short(Props) {
  var classNameOpt = Props.className;
  var player = Props.player;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: className
            }, React.createElement("span", {
                  className: "font-bold"
                }, Utils.uiStr(player.id)));
}

var Short = {
  make: PlayerUI$Short
};

function PlayerUI(Props) {
  var classNameOpt = Props.className;
  var player = Props.player;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: className
            }, React.createElement(PlayerUI$Short, {
                  player: player
                }), React.createElement("div", undefined, React.createElement(DeckUI.make, {
                      deck: player.cards
                    })));
}

var make = PlayerUI;

export {
  Short ,
  make ,
  
}
/* Utils Not a pure module */
