// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CardUI from "./CardUI.mjs";
import * as UiUtils from "../UiUtils.mjs";

function PlayerUI(Props) {
  var player = Props.player;
  return React.createElement("div", undefined, UiUtils.uiStr("id: " + player.id), React.createElement("br", undefined), UiUtils.uiStr("sessionId: " + String(player.sessionId)), React.createElement("br", undefined), React.createElement(CardUI.deck, {
                  deck: player.cards
                }));
}

var make = PlayerUI;

export {
  make ,
  
}
/* react Not a pure module */
