// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../fool/Card.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";
import * as CardUI from "./CardUI.mjs";
import * as Spring from "bs-react-spring/src/Spring.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as ReactDnd from "react-dnd";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactSpring from "react-spring";

function TableUI$DndBeatableCard(Props) {
  var card = Props.card;
  var isDropDisabled = Props.isDropDisabled;
  var beatByClassName = Props.beatByClassName;
  var onDrop = Props.onDrop;
  var match = ReactDnd.useDrop({
        accept: "card",
        drop: (function (item, param) {
            Curry._2(onDrop, card, item);
            
          }),
        canDrop: (function (param, param$1) {
            return !Curry._1(isDropDisabled, card);
          }),
        collect: (function (monitor) {
            return {
                    isDropDisabled: Curry._1(isDropDisabled, card),
                    isDragging: !monitor.isOver({
                          shallow: false
                        }),
                    draggedCard: monitor.getItem(),
                    isOver: monitor.isOver({
                          shallow: false
                        }),
                    isOverCurrent: monitor.isOver({
                          shallow: true
                        })
                  };
          })
      }, []);
  var cProps = match[0];
  return React.createElement("div", {
              ref: match[1],
              className: Utils.cx([
                    beatByClassName,
                    "w-12 h-16"
                  ])
            }, React.createElement(CardUI.EmptyCard.make, {
                  className: Utils.cx([cProps.isOverCurrent && !cProps.isDropDisabled ? "bg-pink-500 opacity-70" : ""])
                }));
}

var DndBeatableCard = {
  make: TableUI$DndBeatableCard
};

var CardTransition = Spring.MakeTransition({});

function makeTransitions(cards) {
  return ReactSpring.useTransition(cards, (function (param) {
                return Card.cardToString(param[0]);
              }), {
              from: {
                opacity: "0",
                transform: "scale(1.5)"
              },
              enter: {
                opacity: "1",
                transform: "scale(1)"
              },
              leave: {
                opacity: "0",
                transform: "scale(1.5)"
              },
              config: {
                tension: 100
              }
            });
}

function TableUI$CardsPair$attacker(Props) {
  var pair = Props.pair;
  var transitions = makeTransitions(Belt_Array.keep([pair], (function (param) {
              return Belt_Option.isSome(param[1]);
            })));
  return React.createElement("div", {
              className: "flex flex-col gap-3 relative"
            }, React.createElement(CardUI.make, {
                  card: pair[0],
                  className: Utils.leftRotationClassName
                }), Belt_Array.map(transitions, (function (param) {
                    var props = param.props;
                    return React.createElement(Spring.Div.make, {
                                className: "absolute left-1 top-1",
                                style: {
                                  opacity: props.opacity,
                                  transform: props.transform
                                },
                                children: React.createElement(CardUI.make, {
                                      card: Belt_Option.getWithDefault(param.item[1], /* Hidden */0),
                                      className: Utils.rightRotationClassName
                                    }),
                                key: param.key
                              });
                  })));
}

function TableUI$CardsPair$defender(Props) {
  var pair = Props.pair;
  var isDropDisabled = Props.isDropDisabled;
  var onDrop = Props.onDrop;
  var by = pair[1];
  var to = pair[0];
  var beatByClassName = Utils.rightRotationClassName + " absolute left-1 top-1";
  return React.createElement("div", {
              className: "flex flex-col gap-3 relative"
            }, by !== undefined ? React.createElement(React.Fragment, {
                    children: null
                  }, React.createElement(CardUI.make, {
                        card: to,
                        className: Utils.leftRotationClassName
                      }), React.createElement("div", {
                        className: beatByClassName
                      }, React.createElement(CardUI.make, {
                            card: by
                          }))) : React.createElement(React.Fragment, {
                    children: null
                  }, React.createElement(CardUI.make, {
                        card: to,
                        className: Utils.leftRotationClassName
                      }), React.createElement(TableUI$DndBeatableCard, {
                        card: to,
                        isDropDisabled: isDropDisabled,
                        beatByClassName: beatByClassName,
                        onDrop: onDrop
                      })));
}

var CardsPair = {
  attacker: TableUI$CardsPair$attacker,
  defender: TableUI$CardsPair$defender
};

function TableUI(Props) {
  var classNameOpt = Props.className;
  var isDefenderOpt = Props.isDefender;
  var isDropDisabledOpt = Props.isDropDisabled;
  var table = Props.table;
  var onDrop = Props.onDrop;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var isDefender = isDefenderOpt !== undefined ? isDefenderOpt : false;
  var isDropDisabled = isDropDisabledOpt !== undefined ? isDropDisabledOpt : (function (param) {
        return true;
      });
  var transitions = makeTransitions(Belt_Array.reverse(Belt_List.toArray(table)));
  return React.createElement("div", {
              className: Utils.cx([
                    "flex gap-1 flex-row",
                    className
                  ])
            }, Belt_Array.map(transitions, (function (param) {
                    var props = param.props;
                    var pair = param.item;
                    return React.createElement(Spring.Div.make, {
                                style: {
                                  opacity: props.opacity,
                                  transform: props.transform
                                },
                                children: isDefender ? React.createElement(TableUI$CardsPair$defender, {
                                        pair: pair,
                                        isDropDisabled: isDropDisabled,
                                        onDrop: onDrop
                                      }) : React.createElement(TableUI$CardsPair$attacker, {
                                        pair: pair
                                      }),
                                key: param.key
                              });
                  })));
}

var make = TableUI;

export {
  DndBeatableCard ,
  CardTransition ,
  makeTransitions ,
  CardsPair ,
  make ,
  
}
/* CardTransition Not a pure module */
