// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../fool/Card.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.mjs";
import * as React from "react";
import * as CardUI from "./CardUI.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactBeautifulDnd from "react-beautiful-dnd";

function TableUI$DndBeatableCard(Props) {
  var card = Props.card;
  var isDropDisabled = Props.isDropDisabled;
  var beatByClassName = Props.beatByClassName;
  return React.createElement(ReactBeautifulDnd.Droppable, {
              droppableId: Card.cardToString(card),
              isDropDisabled: Curry._1(isDropDisabled, card),
              direction: "horizontal",
              children: (function (provided, snapshot) {
                  return React.createElement("div", {
                              ref: provided.innerRef,
                              className: Utils.cx([
                                    beatByClassName,
                                    "w-12 h-16"
                                  ])
                            }, React.createElement(CardUI.Base.make, {
                                  className: Utils.cx([snapshot.isDraggingOver ? "bg-pink-200 opacity-50" : ""]),
                                  children: provided.placeholder
                                }), React.createElement("div", undefined));
                })
            });
}

var DndBeatableCard = {
  make: TableUI$DndBeatableCard
};

function TableUI(Props) {
  var classNameOpt = Props.className;
  var isDropDisabledOpt = Props.isDropDisabled;
  var table = Props.table;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var isDropDisabled = isDropDisabledOpt !== undefined ? isDropDisabledOpt : (function (param) {
        return true;
      });
  var beatByClassName = Utils.rightRotationClassName + " absolute left-1 top-1";
  return React.createElement("div", {
              className: Utils.cx([
                    "flex gap-1 flex-row",
                    className
                  ])
            }, Utils.uiReverseList(table, (function (param) {
                    var by = param[1];
                    var to = param[0];
                    var key = Card.cardToString(to) + Belt_Option.getWithDefault(Belt_Option.map(by, Card.cardToString), "");
                    return React.createElement("div", {
                                key: key,
                                className: "flex flex-col gap-1 relative"
                              }, by !== undefined ? React.createElement(React.Fragment, {
                                      children: null
                                    }, React.createElement(CardUI.make, {
                                          card: to,
                                          className: Utils.leftRotationClassName
                                        }), React.createElement("div", {
                                          className: beatByClassName
                                        }, React.createElement(CardUI.make, {
                                              card: by
                                            }))) : React.createElement(React.Fragment, {
                                      children: null
                                    }, React.createElement(CardUI.make, {
                                          card: to,
                                          className: Utils.leftRotationClassName
                                        }), React.createElement(TableUI$DndBeatableCard, {
                                          card: to,
                                          isDropDisabled: isDropDisabled,
                                          beatByClassName: beatByClassName
                                        })));
                  })));
}

var make = TableUI;

export {
  DndBeatableCard ,
  make ,
  
}
/* react Not a pure module */
