// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MResult from "./MResult.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function toResult(a, b) {
  return Belt_Option.getWithDefault(Belt_Option.map(a, MResult.makeOk), {
              TAG: /* Error */1,
              _0: b
            });
}

export {
  toResult ,
  
}
/* No side effect */
