// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./Card.mjs";
import * as Utils from "../utils/Utils.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function hasCards(table) {
  return Belt_List.length(table) > 0;
}

function isAllBeaten(table) {
  var isBeaten = Belt_List.every(table, (function (param) {
          return Belt_Option.isSome(param[1]);
        }));
  if (Belt_List.length(table) > 0) {
    return isBeaten;
  } else {
    return false;
  }
}

function isMaximumCards(table) {
  return Belt_List.length(table) === 6;
}

function getFlatCards(table) {
  return Belt_List.keepMap(Belt_List.flatten(Belt_List.map(table, (function (param) {
                        return {
                                hd: Caml_option.some(param[0]),
                                tl: {
                                  hd: param[1],
                                  tl: /* [] */0
                                }
                              };
                      }))), Utils.identity);
}

function getUnbeatedCards(table) {
  return Belt_List.map(Belt_List.keep(table, (function (param) {
                    return Belt_Option.isNone(param[1]);
                  })), (function (param) {
                return param[0];
              }));
}

function toObject(table) {
  return Belt_List.toArray(Belt_List.map(table, (function (param) {
                    return [
                            Card.cardToString(param[0]),
                            Belt_Option.getWithDefault(Belt_Option.map(param[1], Card.cardToString), "None")
                          ];
                  })));
}

export {
  hasCards ,
  isAllBeaten ,
  isMaximumCards ,
  getFlatCards ,
  getUnbeatedCards ,
  toObject ,
  
}
/* Utils Not a pure module */
