// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.mjs";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function hasCards(table) {
  return Belt_List.length(table) > 0;
}

function isAllBeaten(table) {
  var isBeaten = Belt_List.every(table, (function (param) {
          return Belt_Option.isSome(param[1]);
        }));
  if (Belt_List.length(table) > 0) {
    return isBeaten;
  } else {
    return false;
  }
}

function isMaximumCards(table) {
  return Belt_List.length(table) === 6;
}

function getFlatCards(table) {
  return Belt_List.keepMap(Belt_List.flatten(Belt_List.map(table, (function (param) {
                        return {
                                hd: param[0],
                                tl: {
                                  hd: param[1],
                                  tl: /* [] */0
                                }
                              };
                      }))), Utils.identity);
}

export {
  hasCards ,
  isAllBeaten ,
  isMaximumCards ,
  getFlatCards ,
  
}
/* No side effect */
