// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

var equals = Caml_obj.caml_equal;

function toggleArrayItem(list, item) {
  var hasItem = Belt_List.has(list, item, equals);
  if (hasItem) {
    return Belt_List.keep(list, (function (i) {
                  return !Caml_obj.caml_equal(i, item);
                }));
  } else {
    return Belt_List.add(list, item);
  }
}

function lastListItem(list) {
  return Belt_List.get(list, Belt_List.size(list) - 1 | 0);
}

function identity(a) {
  return a;
}

export {
  equals ,
  toggleArrayItem ,
  lastListItem ,
  identity ,
  
}
/* No side effect */
