// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

function toggleArrayItem(list, item) {
  var hasItem = Belt_List.has(list, item, (function (first, second) {
          return first === second;
        }));
  if (hasItem) {
    return Belt_List.keep(list, (function (i) {
                  return i !== item;
                }));
  } else {
    return Belt_List.add(list, item);
  }
}

function makeOk(a) {
  return {
          TAG: /* Ok */0,
          _0: a
        };
}

var equals = Caml_obj.caml_equal;

export {
  toggleArrayItem ,
  makeOk ,
  equals ,
  
}
/* No side effect */
