// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RDnd from "./bindings/RDnd.mjs";

var DragObject = {};

var DropResult = {};

var CollectedProps = {};

var include = RDnd.MakeDnd(DragObject, DropResult, CollectedProps);

var Backend = include.Backend;

var Provider = include.Provider;

var DragSourceMonitor = include.DragSourceMonitor;

var DropTargetMonitor = include.DropTargetMonitor;

var UseDrop = include.UseDrop;

var UseDrag = include.UseDrag;

export {
  DragObject ,
  DropResult ,
  CollectedProps ,
  Backend ,
  Provider ,
  DragSourceMonitor ,
  DropTargetMonitor ,
  UseDrop ,
  UseDrag ,
  
}
/* include Not a pure module */
