// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./fool/Card.mjs";
import * as Game from "./fool/Game.mjs";
import * as React from "react";
import * as Player from "./fool/Player.mjs";
import * as UiUtils from "./UiUtils.mjs";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

function Examples$CardUI(Props) {
  var classNameOpt = Props.className;
  var card = Props.card;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: UiUtils.cx([
                    "card",
                    Card.suitToString(card[0]),
                    className
                  ])
            }, React.createElement("div", {
                  className: "suit"
                }, UiUtils.uiStr(Card.suitToString(card[0]))), React.createElement("div", {
                  className: "rank"
                }, UiUtils.uiStr(Card.rankToString(card[1]))));
}

function Examples$CardUI$trump(Props) {
  var classNameOpt = Props.className;
  var suit = Props.suit;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: UiUtils.cx([
                    "card",
                    Card.suitToString(suit),
                    className
                  ])
            }, React.createElement("div", {
                  className: "suit"
                }, UiUtils.uiStr(Card.suitToString(suit))), React.createElement("div", {
                  className: "rank"
                }, UiUtils.uiStr("")));
}

function Examples$DeckUI(Props) {
  var deck = Props.deck;
  if (deck) {
    return React.createElement("div", undefined, UiUtils.uiList(deck, (function (card) {
                      return React.createElement(Examples$CardUI, {
                                  className: "deck-card",
                                  card: card,
                                  key: Card.cardToString(card)
                                });
                    })));
  } else {
    return React.createElement("div", undefined, UiUtils.uiStr("No cards in deck"));
  }
}

function Examples$PlayerUI(Props) {
  var player = Props.player;
  return React.createElement("div", undefined, UiUtils.uiStr("id: " + player.id), React.createElement("br", undefined), UiUtils.uiStr("sessionId: " + String(player.sessionId)), React.createElement("br", undefined), React.createElement(Examples$DeckUI, {
                  deck: player.cards
                }));
}

function Examples$InLobbyUI(Props) {
  var game = Props.game;
  return React.createElement("div", undefined, UiUtils.uiStr("inLobby"), React.createElement("br", undefined), React.createElement("br", undefined), UiUtils.uiStr("players:"), React.createElement("br", undefined), React.createElement("div", undefined, UiUtils.uiList(game.players, (function (p) {
                        return React.createElement(Examples$PlayerUI, {
                                    player: p
                                  });
                      }))), React.createElement("br", undefined), UiUtils.uiStr("ready:"), React.createElement("br", undefined), React.createElement("div", undefined, UiUtils.uiList(game.ready, (function (p) {
                        return React.createElement(Examples$PlayerUI, {
                                    player: p
                                  });
                      }))));
}

function Examples$InProgressUI(Props) {
  var game = Props.game;
  return React.createElement("div", undefined, UiUtils.uiStr("inProgress"), React.createElement("br", undefined), React.createElement("br", undefined), UiUtils.uiStr("deck:"), React.createElement("br", undefined), React.createElement("div", undefined, React.createElement(Examples$DeckUI, {
                      deck: game.deck
                    })), UiUtils.uiStr("players:"), React.createElement("br", undefined), React.createElement("div", undefined, UiUtils.uiList(game.players, (function (p) {
                        return React.createElement(Examples$PlayerUI, {
                                    player: p
                                  });
                      }))), React.createElement("br", undefined), UiUtils.uiStr("trump:"), React.createElement("br", undefined), React.createElement(Examples$CardUI$trump, {
                  suit: game.trump
                }));
}

function Examples$GameUI(Props) {
  var game = Props.game;
  if (game.TAG === /* InLobby */0) {
    return React.createElement(Examples$InLobbyUI, {
                game: game._0
              });
  } else {
    return React.createElement(Examples$InProgressUI, {
                game: game._0
              });
  }
}

var players_0 = Player.make("aaa");

var players_1 = {
  hd: Player.make("bbb"),
  tl: {
    hd: Player.make("ccc"),
    tl: /* [] */0
  }
};

var players = {
  hd: players_0,
  tl: players_1
};

var gameInProgress = Belt_Result.getExn(Game.startGame({
          players: players,
          ready: players
        }));

var gameInLobby = Game.makeGameInLobby("owner");

function $$default(param) {
  return React.createElement("div", undefined, React.createElement(Examples$GameUI, {
                  game: gameInProgress
                }), React.createElement("br", undefined), React.createElement(Examples$GameUI, {
                  game: gameInLobby
                }));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                none: 0
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* players Not a pure module */
