// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";
import * as Utils from "./Utils.mjs";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_MutableMap from "rescript/lib/es6/belt_MutableMap.js";

function MakeGameMap(Item) {
  var cmp = Caml.caml_string_compare;
  var GameId = Belt_Id.MakeComparable({
        cmp: cmp
      });
  var empty = function (param) {
    return Belt_MutableMap.make(GameId);
  };
  var get = function (map, gameId) {
    return Utils.toResult(Belt_MutableMap.get(map, gameId), "Game \"" + gameId + "\" not found");
  };
  var set = function (map, game) {
    return function (param) {
      return Belt_MutableMap.set(map, game, param);
    };
  };
  return {
          GameId: GameId,
          empty: empty,
          get: get,
          set: set
        };
}

export {
  MakeGameMap ,
  
}
/* No side effect */
