// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Router from "next/router";
import * as PlayerScreen from "./PlayerScreen.mjs";

function $$default(param) {
  var router = Router.useRouter();
  var gameId = Js_dict.get(router.query, "gameId");
  console.log(router.query);
  var onConnect = function (sendMessage, player) {
    if (gameId !== undefined && player !== undefined) {
      return Curry._1(sendMessage, {
                  TAG: /* Lobby */1,
                  _0: /* Enter */1,
                  _1: player.id,
                  _2: gameId
                });
    }
    
  };
  return React.createElement(PlayerScreen.make, {
              onConnect: onConnect
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
