// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Router from "next/router";
import * as PlayerScreen from "./PlayerScreen.mjs";

function $$default(param) {
  var router = Router.useRouter();
  var gameId = Js_dict.get(router.query, "gameId");
  return React.createElement(PlayerScreen.make, {
              gameId: gameId
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
