// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDnd from "react-dnd";
import * as PlayerScreen from "./PlayerScreen.mjs";
import * as ReactDndHtml5Backend from "react-dnd-html5-backend";

function $$default(param) {
  return React.createElement("div", {
              className: "flex flex-row flex-wrap justify-items-center w-full container px-12 py-6 gap-12"
            }, React.createElement(ReactDnd.DndProvider, {
                  backend: ReactDndHtml5Backend.HTML5Backend,
                  children: React.createElement(PlayerScreen.make, {
                        gameId: "g1",
                        sessionId: "s:p1"
                      })
                }));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
