// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

function makeOk(a) {
  return {
          TAG: /* Ok */0,
          _0: a
        };
}

function tap(result, fn) {
  return Belt_Result.map(result, (function (content) {
                Curry._1(fn, content);
                return content;
              }));
}

function tapError(result, fn) {
  if (result.TAG !== /* Ok */0) {
    Curry._1(fn, result._0);
  }
  return result;
}

function fold(result, onOk, onError) {
  if (result.TAG === /* Ok */0) {
    return Curry._1(onOk, result._0);
  } else {
    return Curry._1(onError, result._0);
  }
}

export {
  makeOk ,
  tap ,
  tapError ,
  fold ,
  
}
/* No side effect */
