// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "rescript-jzon/src/Jzon.mjs";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function suitToString(suit) {
  switch (suit) {
    case /* Spades */0 :
        return "S";
    case /* Hearts */1 :
        return "H";
    case /* Diamonds */2 :
        return "D";
    case /* Clubs */3 :
        return "C";
    
  }
}

function stringToSuit(str) {
  switch (str) {
    case "C" :
        return /* Clubs */3;
    case "D" :
        return /* Diamonds */2;
    case "H" :
        return /* Hearts */1;
    case "S" :
        return /* Spades */0;
    default:
      return ;
  }
}

function rankToString(rank) {
  switch (rank) {
    case /* Six */0 :
        return "6";
    case /* Seven */1 :
        return "7";
    case /* Eight */2 :
        return "8";
    case /* Nine */3 :
        return "9";
    case /* Ten */4 :
        return "10";
    case /* Jack */5 :
        return "J";
    case /* Queen */6 :
        return "Q";
    case /* King */7 :
        return "K";
    case /* Ace */8 :
        return "A";
    
  }
}

function stringToRank(str) {
  switch (str) {
    case "10" :
        return /* Ten */4;
    case "6" :
        return /* Six */0;
    case "7" :
        return /* Seven */1;
    case "8" :
        return /* Eight */2;
    case "9" :
        return /* Nine */3;
    case "A" :
        return /* Ace */8;
    case "J" :
        return /* Jack */5;
    case "K" :
        return /* King */7;
    case "Q" :
        return /* Queen */6;
    default:
      return ;
  }
}

function cardToString(card) {
  if (!card) {
    return "hidden";
  }
  var match = card._0;
  return suitToString(match[0]) + rankToString(match[1]);
}

function stringToCard(str) {
  if (str === "hidden") {
    return {
            TAG: /* Ok */0,
            _0: /* Hidden */0
          };
  }
  var suit = stringToSuit(str.slice(0, 1));
  var rank = stringToRank(str.slice(1, 3));
  if (suit !== undefined) {
    if (rank !== undefined) {
      return {
              TAG: /* Ok */0,
              _0: /* Visible */{
                _0: [
                  suit,
                  rank
                ]
              }
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: {
                NAME: "UnexpectedJsonValue",
                VAL: [
                  [{
                      TAG: /* Field */0,
                      _0: "rank"
                    }],
                  str
                ]
              }
            };
    }
  } else {
    return {
            TAG: /* Error */1,
            _0: {
              NAME: "UnexpectedJsonValue",
              VAL: [
                [{
                    TAG: /* Field */0,
                    _0: "suit"
                  }],
                str
              ]
            }
          };
  }
}

var card = Jzon.custom(cardToString, (function (json) {
        return stringToCard(Belt_Option.getWithDefault(Js_json.decodeString(json), ""));
      }));

var beat = Jzon.object2((function (param) {
        return [
                param.to,
                param.by
              ];
      }), (function (param) {
        return {
                TAG: /* Ok */0,
                _0: {
                  to: param[0],
                  by: param[1]
                }
              };
      }), Jzon.field("to", card), Jzon.field("by", card));

var move = Jzon.object1((function (param) {
        return param.card;
      }), (function (card) {
        return {
                TAG: /* Ok */0,
                _0: {
                  card: card
                }
              };
      }), Jzon.field("card", card));

var msg = Jzon.object2((function (kind) {
        if (typeof kind === "number") {
          if (kind === /* Take */0) {
            return [
                    "take",
                    undefined
                  ];
          } else {
            return [
                    "pass",
                    undefined
                  ];
          }
        } else if (kind.TAG === /* Beat */0) {
          return [
                  "beat",
                  Caml_option.some(Jzon.encodeWith({
                            to: kind._0,
                            by: kind._1
                          }, beat))
                ];
        } else {
          return [
                  "move",
                  Caml_option.some(Jzon.encodeWith({
                            card: kind._0
                          }, move))
                ];
        }
      }), (function (param) {
        var payload = param[1];
        var kind = param[0];
        switch (kind) {
          case "beat" :
              if (payload !== undefined) {
                return Belt_Result.map(Jzon.decodeWith(Caml_option.valFromOption(payload), beat), (function (param) {
                              return {
                                      TAG: /* Beat */0,
                                      _0: param.to,
                                      _1: param.by
                                    };
                            }));
              }
              break;
          case "move" :
              if (payload !== undefined) {
                return Belt_Result.map(Jzon.decodeWith(Caml_option.valFromOption(payload), move), (function (param) {
                              return {
                                      TAG: /* Move */1,
                                      _0: param.card
                                    };
                            }));
              }
              break;
          case "pass" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Pass */1
                    };
          case "take" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Take */0
                    };
          default:
            
        }
        return {
                TAG: /* Error */1,
                _0: {
                  NAME: "UnexpectedJsonValue",
                  VAL: [
                    [{
                        TAG: /* Field */0,
                        _0: "kind"
                      }],
                    kind
                  ]
                }
              };
      }), Jzon.field("kind", Jzon.string), Jzon.optional(Jzon.field("payload", Jzon.json)));

var Codecs = {
  suitToString: suitToString,
  stringToSuit: stringToSuit,
  rankToString: rankToString,
  stringToRank: stringToRank,
  cardToString: cardToString,
  stringToCard: stringToCard,
  card: card,
  beat: beat,
  move: move,
  msg: msg
};

export {
  Codecs ,
  
}
/* card Not a pure module */
