// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "rescript-jzon/src/Jzon.mjs";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function suitToString(suit) {
  switch (suit) {
    case /* Spades */0 :
        return "S";
    case /* Hearts */1 :
        return "H";
    case /* Diamonds */2 :
        return "D";
    case /* Clubs */3 :
        return "C";
    
  }
}

function stringToSuit(str) {
  switch (str) {
    case "C" :
        return /* Clubs */3;
    case "D" :
        return /* Diamonds */2;
    case "H" :
        return /* Hearts */1;
    case "S" :
        return /* Spades */0;
    default:
      return ;
  }
}

function rankToString(rank) {
  switch (rank) {
    case /* Six */0 :
        return "6";
    case /* Seven */1 :
        return "7";
    case /* Eight */2 :
        return "8";
    case /* Nine */3 :
        return "9";
    case /* Ten */4 :
        return "10";
    case /* Jack */5 :
        return "J";
    case /* Queen */6 :
        return "Q";
    case /* King */7 :
        return "K";
    case /* Ace */8 :
        return "A";
    
  }
}

function stringToRank(str) {
  switch (str) {
    case "10" :
        return /* Ten */4;
    case "6" :
        return /* Six */0;
    case "7" :
        return /* Seven */1;
    case "8" :
        return /* Eight */2;
    case "9" :
        return /* Nine */3;
    case "A" :
        return /* Ace */8;
    case "J" :
        return /* Jack */5;
    case "K" :
        return /* King */7;
    case "Q" :
        return /* Queen */6;
    default:
      return ;
  }
}

function cardToString(card) {
  if (!card) {
    return "hidden";
  }
  var match = card._0;
  return suitToString(match[0]) + rankToString(match[1]);
}

function stringToCard(str) {
  if (str === "hidden") {
    return {
            TAG: /* Ok */0,
            _0: /* Hidden */0
          };
  }
  var suit = stringToSuit(str.slice(0, 1));
  var rank = stringToRank(str.slice(1, 3));
  if (suit !== undefined) {
    if (rank !== undefined) {
      return {
              TAG: /* Ok */0,
              _0: /* Visible */{
                _0: [
                  suit,
                  rank
                ]
              }
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: {
                NAME: "UnexpectedJsonValue",
                VAL: [
                  [{
                      TAG: /* Field */0,
                      _0: "rank"
                    }],
                  str
                ]
              }
            };
    }
  } else {
    return {
            TAG: /* Error */1,
            _0: {
              NAME: "UnexpectedJsonValue",
              VAL: [
                [{
                    TAG: /* Field */0,
                    _0: "suit"
                  }],
                str
              ]
            }
          };
  }
}

var card = Jzon.custom(cardToString, (function (json) {
        return stringToCard(Belt_Option.getWithDefault(Js_json.decodeString(json), ""));
      }));

var playerMsg = Jzon.object1((function (kind) {
        switch (kind) {
          case /* Connect */0 :
              return "connect";
          case /* Disconnect */1 :
              return "disconnect";
          case /* Ping */2 :
              return "ping";
          case /* Pong */3 :
              return "pong";
          
        }
      }), (function (kind) {
        switch (kind) {
          case "Pong" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Pong */3
                    };
          case "connect" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Connect */0
                    };
          case "disconnect" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Disconnect */1
                    };
          case "ping" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Ping */2
                    };
          default:
            return {
                    TAG: /* Error */1,
                    _0: {
                      NAME: "UnexpectedJsonValue",
                      VAL: [
                        [{
                            TAG: /* Field */0,
                            _0: "kind"
                          }],
                        kind
                      ]
                    }
                  };
        }
      }), Jzon.field("kind", Jzon.string));

var lobbyMsg = Jzon.object1((function (kind) {
        switch (kind) {
          case /* Create */0 :
              return "create";
          case /* Enter */1 :
              return "enter";
          case /* Ready */2 :
              return "ready";
          case /* Start */3 :
              return "start";
          
        }
      }), (function (kind) {
        switch (kind) {
          case "create" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Create */0
                    };
          case "enter" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Enter */1
                    };
          case "ready" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Ready */2
                    };
          case "start" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Start */3
                    };
          default:
            return {
                    TAG: /* Error */1,
                    _0: {
                      NAME: "UnexpectedJsonValue",
                      VAL: [
                        [{
                            TAG: /* Field */0,
                            _0: "kind"
                          }],
                        kind
                      ]
                    }
                  };
        }
      }), Jzon.field("kind", Jzon.string));

var beatPayload = Jzon.object2((function (param) {
        return [
                param.to,
                param.by
              ];
      }), (function (param) {
        return {
                TAG: /* Ok */0,
                _0: {
                  to: param[0],
                  by: param[1]
                }
              };
      }), Jzon.field("to", card), Jzon.field("by", card));

var movePayload = Jzon.object1((function (param) {
        return param.card;
      }), (function (card) {
        return {
                TAG: /* Ok */0,
                _0: {
                  card: card
                }
              };
      }), Jzon.field("card", card));

var progressMsg = Jzon.object2((function (kind) {
        if (typeof kind === "number") {
          if (kind === /* Pass */0) {
            return [
                    "pass",
                    undefined
                  ];
          } else {
            return [
                    "take",
                    undefined
                  ];
          }
        } else if (kind.TAG === /* Beat */0) {
          return [
                  "beat",
                  Caml_option.some(Jzon.encodeWith(kind._0, beatPayload))
                ];
        } else {
          return [
                  "move",
                  Caml_option.some(Jzon.encodeWith(kind._0, movePayload))
                ];
        }
      }), (function (param) {
        var payload = param[1];
        var kind = param[0];
        switch (kind) {
          case "beat" :
              if (payload !== undefined) {
                return Belt_Result.map(Jzon.decodeWith(Caml_option.valFromOption(payload), beatPayload), (function (param) {
                              return {
                                      TAG: /* Beat */0,
                                      _0: {
                                        to: param.to,
                                        by: param.by
                                      }
                                    };
                            }));
              }
              break;
          case "move" :
              if (payload !== undefined) {
                return Belt_Result.map(Jzon.decodeWith(Caml_option.valFromOption(payload), movePayload), (function (param) {
                              return {
                                      TAG: /* Move */1,
                                      _0: {
                                        card: param.card
                                      }
                                    };
                            }));
              }
              break;
          case "pass" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Pass */0
                    };
          case "take" :
              return {
                      TAG: /* Ok */0,
                      _0: /* Take */1
                    };
          default:
            
        }
        return {
                TAG: /* Error */1,
                _0: {
                  NAME: "UnexpectedJsonValue",
                  VAL: [
                    [{
                        TAG: /* Field */0,
                        _0: "kind"
                      }],
                    kind
                  ]
                }
              };
      }), Jzon.field("kind", Jzon.string), Jzon.optional(Jzon.field("payload", Jzon.json)));

var gameMsg = Jzon.object4((function (kind) {
        switch (kind.TAG | 0) {
          case /* Player */0 :
              return [
                      "player",
                      Jzon.encodeWith(kind._0, playerMsg),
                      kind._1,
                      undefined
                    ];
          case /* Lobby */1 :
              return [
                      "lobby",
                      Jzon.encodeWith(kind._0, lobbyMsg),
                      kind._1,
                      kind._2
                    ];
          case /* Progress */2 :
              return [
                      "progress",
                      Jzon.encodeWith(kind._0, progressMsg),
                      kind._1,
                      kind._2
                    ];
          
        }
      }), (function (param) {
        var gameId = param[3];
        var playerId = param[2];
        var msg = param[1];
        var kind = param[0];
        switch (kind) {
          case "lobby" :
              if (gameId !== undefined) {
                return Belt_Result.map(Jzon.decodeWith(msg, lobbyMsg), (function (msg) {
                              return {
                                      TAG: /* Lobby */1,
                                      _0: msg,
                                      _1: playerId,
                                      _2: gameId
                                    };
                            }));
              }
              break;
          case "player" :
              return Belt_Result.map(Jzon.decodeWith(msg, playerMsg), (function (msg) {
                            return {
                                    TAG: /* Player */0,
                                    _0: msg,
                                    _1: playerId
                                  };
                          }));
          case "progress" :
              if (gameId !== undefined) {
                return Belt_Result.map(Jzon.decodeWith(msg, progressMsg), (function (msg) {
                              return {
                                      TAG: /* Progress */2,
                                      _0: msg,
                                      _1: playerId,
                                      _2: gameId
                                    };
                            }));
              }
              break;
          default:
            
        }
        return {
                TAG: /* Error */1,
                _0: {
                  NAME: "UnexpectedJsonValue",
                  VAL: [
                    [{
                        TAG: /* Field */0,
                        _0: "kind"
                      }],
                    kind
                  ]
                }
              };
      }), Jzon.field("kind", Jzon.string), Jzon.field("payload", Jzon.json), Jzon.field("playerId", Jzon.string), Jzon.optional(Jzon.field("gameId", Jzon.string)));

var Codecs = {
  suitToString: suitToString,
  stringToSuit: stringToSuit,
  rankToString: rankToString,
  stringToRank: stringToRank,
  cardToString: cardToString,
  stringToCard: stringToCard,
  card: card,
  playerMsg: playerMsg,
  lobbyMsg: lobbyMsg,
  beatPayload: beatPayload,
  movePayload: movePayload,
  progressMsg: progressMsg,
  gameMsg: gameMsg
};

export {
  Codecs ,
  
}
/* card Not a pure module */
