// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function MainLayout(Props) {
  var children = Props.children;
  var minWidth = {
    minWidth: "20rem"
  };
  return React.createElement("main", {
              className: "s-full flex justify-center text-gray-900 font-base",
              style: minWidth
            }, children);
}

var make = MainLayout;

export {
  make ,
  
}
/* react Not a pure module */
